version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres14
    environment:
      POSTGRES_DB: ${POSTGRES_LOCALHOST_DATABASE}
      POSTGRES_USER: ${POSTGRES_LOCALHOST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_LOCALHOST_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  liquibase:
    build: .
    container_name: liquibase
    depends_on:
      - postgres
    working_dir: /liquibase
    volumes:
      - .:/app
      - ./src/database/liquibase:/liquibase
    entrypoint:
      - /app/wait-for-postgres.sh
      - postgres
      - "5432"
      - liquibase
      - --defaultsFile=/liquibase/liquibase.properties
      - update
  app:
    build: .
    container_name: nest-app
    depends_on:
      - postgres
      - liquibase
    environment:
      PORT: ${DEFAULT_PORT}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_LOCALHOST_USER}
      DB_PASSWORD: ${POSTGRES_LOCALHOST_PASSWORD}
      DB_NAME: ${POSTGRES_LOCALHOST_DATABASE}
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: npm run start:dev

volumes:
  pgdata: